[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["SquadGame"]
optimizer = true
optimizer_runs = 20000
solc = "0.8.21"


fs_permissions = [{ access = "read", path = "lib/foundry-chainlink-toolkit/out"}]

# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config